[package]
name = "cargo-http-registry"
version = "0.1.5"
authors = ["Daniel Mueller <deso@posteo.net>"]
edition = "2021"
rust-version = "1.63"
license = "GPL-3.0-or-later"
homepage = "https://github.com/d-e-s-o/cargo-http-registry"
repository = "https://github.com/d-e-s-o/cargo-http-registry.git"
readme = "README.md"
categories = [
  "command-line-utilities",
  "config",
  "database",
  "development-tools",
  "filesystem",
]
keywords = [
  "cargo",
  "registry",
  "registry-server",
  "http",
  "filesystem",
]
description = """
A cargo registry allowing for quick publishing of crates when using
crates.io is just not desired.
"""

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
incremental = false

[dependencies]
anyhow = {version = "1.0.14"}
git2 = {version = "0.17"}
serde = {version = "1.0.103", features = ["derive"]}
serde_json = {version = "1.0"}
sha2 = {version = "0.10"}
structopt = {version = "0.3.20"}
tokio = {version = "1.0", default-features = false, features = ["rt"]}
tracing = {version = "0.1.18", default-features = false, features = ["std"]}
tracing-subscriber = {version = "0.3", default-features = false, features = ["ansi", "env-filter", "fmt"]}
warp = {version = "0.3", default-features = false}

[dev-dependencies]
tempfile = {version = "3.1"}
tokio = {version = "1.0", default-features = false, features = ["macros", "rt"]}
